{{- if .Values.audit.testWebhookReceiver.enabled }}
{{- $svcName := include "apiservice-audit-proxy.testWebhookReceiver.fullname" . }}
{{- $namespace := .Release.Namespace }}
{{- $port := .Values.audit.testWebhookReceiver.service.port | int }}
{{- $sessionUUID := required "audit.testWebhookReceiver.proxySessionUUID is required when audit.testWebhookReceiver.enabled=true" .Values.audit.testWebhookReceiver.proxySessionUUID }}
{{- $secretName := required "audit.webhook.kubeconfigSecretName is required" .Values.audit.webhook.kubeconfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "apiservice-audit-proxy.testWebhookReceiver.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.audit.webhook.kubeconfigKey }}: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - name: webhook-tester
      cluster:
        server: http://{{ $svcName }}.{{ $namespace }}.svc.cluster.local:{{ $port }}/{{ $sessionUUID }}
    contexts:
    - name: webhook
      context:
        cluster: webhook-tester
        user: default
    current-context: webhook
    users:
    - name: default
      user: {}
{{- end }}
