apiVersion: v2
name: apiservice-audit-proxy
description: >-
  An aggregated API pass-through proxy that emits richer audit.k8s.io/v1
  ResponseComplete events for supported mutating requests
type: application
version: 0.2.0
appVersion: 0.2.0
keywords:
  - kubernetes
  - audit
  - apiserver
  - aggregation
  - proxy
home: https://github.com/ConfigButler/apiservice-audit-proxy
sources:
  - https://github.com/ConfigButler/apiservice-audit-proxy
maintainers:
  - name: ConfigButler Team
    url: https://github.com/configbutler
annotations:
  org.opencontainers.image.source: https://github.com/ConfigButler/apiservice-audit-proxy
  org.opencontainers.image.description: Audit pass-through aggregated API server
