apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiservice-audit-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiservice-audit-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: api
      port: {{ .Values.server.service.port }}
      targetPort: api
      protocol: TCP
    {{- if and .Values.server.metrics.listenAddress (ne (toString .Values.server.metrics.listenAddress) "0") }}
    - name: metrics
      port: {{ .Values.server.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "apiservice-audit-proxy.selectorLabels" . | nindent 4 }}
