{{- if .Values.testApiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiservice-audit-proxy.testApiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiservice-audit-proxy.testApiserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.testApiserver.service.type }}
  selector:
    {{- include "apiservice-audit-proxy.testApiserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.testApiserver.service.port | int }}
      protocol: TCP
      targetPort: https
{{- end }}
