{{- if eq (include "apiservice-audit-proxy.certificateMode" .) "cert-manager" }}
{{- if .Values.server.tls.certManager.createSelfSignedIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "apiservice-audit-proxy.servingIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiservice-audit-proxy.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "apiservice-audit-proxy.servingCertificateName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apiservice-audit-proxy.labels" . | nindent 4 }}
spec:
  secretName: {{ include "apiservice-audit-proxy.servingSecretName" . }}
  duration: {{ .Values.server.tls.certManager.duration }}
  renewBefore: {{ .Values.server.tls.certManager.renewBefore }}
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: {{ include "apiservice-audit-proxy.servingIssuerName" . }}
    kind: {{ .Values.server.tls.certManager.issuerRef.kind }}
    group: {{ .Values.server.tls.certManager.issuerRef.group }}
  dnsNames:
    {{- include "apiservice-audit-proxy.servingDNSNames" . | nindent 4 }}
{{- end }}
