{{- if .Values.metrics.vmServiceScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "apiservice-audit-proxy.fullname" . }}
  namespace: {{ .Values.metrics.vmServiceScrape.namespace | default .Release.Namespace }}
  labels:
    {{- include "apiservice-audit-proxy.labels" . | nindent 4 }}
    {{- with .Values.metrics.vmServiceScrape.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "apiservice-audit-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.metrics.vmServiceScrape.port | default "metrics" }}
      path: {{ .Values.metrics.vmServiceScrape.path | default "/metrics" }}
      scheme: {{ .Values.metrics.vmServiceScrape.scheme | default "http" }}
      interval: {{ .Values.metrics.vmServiceScrape.interval }}
      {{- with .Values.metrics.vmServiceScrape.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
