{{- if .Values.webhookTester.enabled }}
{{- $svcName := include "apiservice-audit-proxy.webhookTester.fullname" . }}
{{- $namespace := .Release.Namespace }}
{{- $port := .Values.webhookTester.service.port | int }}
{{- $sessionUUID := required "webhookTester.proxySessionUUID is required when webhookTester.enabled=true" .Values.webhookTester.proxySessionUUID }}
{{- $secretName := required "webhook.kubeconfigSecretName is required" .Values.webhook.kubeconfigSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "apiservice-audit-proxy.webhookTester.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhook.kubeconfigKey }}: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - name: webhook-tester
      cluster:
        server: http://{{ $svcName }}.{{ $namespace }}.svc.cluster.local:{{ $port }}/{{ $sessionUUID }}
    contexts:
    - name: webhook
      context:
        cluster: webhook-tester
        user: default
    current-context: webhook
    users:
    - name: default
      user: {}
{{- end }}
